### ISSUE TITLE
I always get a redirect

### ISSUE THREAD

**Issue by lioman** [pinax/django-user-accounts#147]
If I activate the sites framework and change the URL from example.com I can not get to account/login or signup and I am redirected to home.
This happens only if I change the URL! Other apps works it must be something in django-user-accounts!

**Comment by bmritz** [comment]
What was the solution here? I'm getting the same problem. I'm running a development server on 0.0.0.0, and when I try to navigate to 0.0.0.0/account/signup, I am redirected to /

**Comment by bmritz** [comment]
I figured it out -- for some reason the URL automatically redirected when I tried 0.0.0.0:8000/account/signup, but when I tried localhost:8000/account/signup, it worked.
