### ISSUE TITLE
No email notification for password changes done via PasswordResetTokenView

### ISSUE THREAD

**Issue by madprime** [pinax/django-user-accounts#152]
PasswordChangeView and PasswordResetTokenView are two different ways users may change their passwords. They both trigger identical messages ("Password successfully changed."), but the latter doesn't perform a notification email when `ACCOUNT_NOTIFY_ON_PASSWORD_CHANGE = True`.

Is this behavior intended? I suspect it's not the behavior a website developer using this package would have expected from this setting, and it's not consistent with how both views are performing identical notifications via messages.

I'd like to submit a pull request (bugfix or feature, depending on how you view this), but would like to know which of these options is preferred:
1. PasswordResetTokenView sends the same "password_change" email (i.e. using the same email templates) based on the `ACCOUNT_NOTIFY_ON_PASSWORD_CHANGE` setting.
2. PasswordResetTokenView sends the same "password_change" email based on a new setting, `ACCOUNT_NOTIFY_ON_RESET_PASSWORD_CHANGE`, and this is set to default to the same value as `ACCOUNT_NOTIFY_ON_PASSWORD_CHANGE`.
3. PasswordResetTokenView sends the same "password_change" email based on a new setting, `ACCOUNT_NOTIFY_ON_RESET_PASSWORD_CHANGE`, and this is set to default to `False`.
4. Something else (e.g. make new email templates).

My preference would be the first option, since this looks like an unintended behavior (bug) to me.

In particular, I'd like to point out that the password reset email [as drafted by pinax-theme-bootstrap-account](https://github.com/pinax/pinax-theme-bootstrap-account/blob/master/pinax_theme_bootstrap_account/templates/account/email/password_reset.txt) tells the user that the reset request *"can be safely ignored if you did not request a password reset"*. With the current behavior, this isn't entirely true. If a user's account is being usurped by someone who has gained access to their email, they won't receive any subsequent notification that a password change event has occurred, and thus won't be alerted to an account breach. That's why I think this is a bug which should be fixed.

**Comment by brosner** [comment]
I would agree with the conclusion that this is unintended behavior. A password reset should behave similar to change password in this respect. I will merge your PR as I agree with that solution.
