### ISSUE TITLE
TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by carpincho** [pinax/django-user-accounts#170]
While applying a migration to django project (1, 7, 0, 'final', 0) I got that type error.
After digging a little bit I found that EmailConfirmation model was using default=timezone.now().
I tried changing that to a callable  and that fixed my migration problem.
Shouldn't be default=timezone.now?
Btw, I have installed django-user-accounts version 1.0.1.

**Comment by brosner** [comment]
This is fixed in 36eee9a88c9600bc75e594116d4ee77f9dd5e231.
