### ISSUE TITLE
Use PasswordField from django-passwords if available

### ISSUE THREAD

**Issue by csghormley** [pinax/django-user-accounts#174]
I have been using django-user-accounts for some time and now I am adding several enhancements to security on my sites. So now I need to add password complexity requirements -- neatly handled by [django-passwords](https://github.com/dstufft/django-passwords).

My approach was to use django-passwords' PasswordField in the SignupForm and ChangePasswordForm. If it's not available, I fall back to the current behavior (CharField).

These changes are in [my use-django-passwords branch](https://github.com/csghormley/django-user-accounts/tree/use-django-passwords). I will submit a pull request or work on further changes as needed if this looks useful.

**Comment by brosner** [comment]
Thank you very much for the contribution. I really appreciate it! However, I would like to avoid bundling this specific logic for passwords. The correct way to handle your password requirements is to subclass the forms that have password fields which write to the DB. You can then reassign the field used for it and gain the awesome features it provides.

**Comment by csghormley** [comment]
I get this is the more flexible design. But password complexity is an almost ubiquitous requirement. It seems sensible to include it here in some fashion. There are not so many ways of doing it that many people will subclass a validator provided with this app if written sensibly.

The options included in django-passwords aren't perfect (what's the difference between punctuation and special characters?) but they give you the common options. 

Has nobody else asked for this?

**Comment by luzfcb** [comment]
a little information: the subject of adding on Django, "best" ways to validate passwords, and create your own validation rules was being discussed in the django-developers mail list: 

https://groups.google.com/d/msg/django-developers/9GBhgGXmEKs/-ZkypIVAy9QJ

**Comment by csghormley** [comment]
Looks like my point was moot. Thanks for the link!

**Comment by brosner** [comment]
For the record, I am not against password requirements and understand that many people would like to enforce something. I am just quite hesitant to pointing people to a single implementation that I or any of my team have used before. Making the decision between "leaving it up to you" and "including something that introduces edge cases that make it annoying" is easy, let's go with the former to save the headache.

I wasn't aware of discussions on including something in Django. I would be willing to backport anything included in a future version of Django to allow all users of django-user-accounts to reap the benefits. Thanks for the link @luzfcb.

**Comment by ludovicthomas** [comment]
@brosner I'm bringing back the topic, as since there is now a settings AUTH_PASSWORD_VALIDATORS to enable password validation from Django. https://docs.djangoproject.com/fr/2.0/topics/auth/passwords/#enabling-password-validation
I was surprised that it's not used by django-user-accounts. As you mentioned I will subclass the form, but would be nice to use the default behavior. Thanks.
