### ISSUE TITLE
Please tag pypi releases

### ISSUE THREAD

**Issue by samuelcolvin** [pinax/django-user-accounts#176]
It's really hard to track down bugs when it's not clear which commit was released.

Please can you tag pipy releases in git.

For example which commit is pypi 1.0.2?

**Comment by brosner** [comment]
I have tagged all releases to date. I will make sure we tag future releases as well.

**Comment by luzfcb** [comment]
very simple approach

https://github.com/pydanny/cookiecutter-djangopackage/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/setup.py#L16-L25
