### ISSUE TITLE
Empty pl_PL (and not needed) translation overrides correct pl translation

### ISSUE THREAD

**Issue by m-aciek** [pinax/django-user-accounts#182]
Hi, thanks for great package,

Recently I spotted that Polish translation isn't working at all ('pl' locale). The problem is the presence of empty 'pl_PL' translation. I'd like to ask you to remove whole pl_PL directory to get Polish django-user-accounts to work correctly.

**Comment by paltman** [comment]
This is now fixed in 1.3.  @m-aciek thanks!
