### ISSUE TITLE
Cannot find code and templates in project

### ISSUE THREAD

**Issue by GraphGrail** [pinax/django-user-accounts#192]
Very strange: i installed project with this instruction: 
http://pinaxproject.com/pinax/quick_start/

and now I want to alter templates of 'account' app - this is django-user-accounts if i right.
But i cannot find files of this app - not in my project dir, not on python site-packages.
So, how do i change models?
Is it right way to download django-user-accounts from Github and put into my Django project

**Comment by jtauber** [comment]
Nothing strange, it's just how virtualenv and pip work. The code is in your virtualenv just like the standard library is.

If you just need to override templates, you can do so in your project.

However, if you are wanting to make changes to models, you'll need to fork the repo and make your own. You shouldn't need to do that, though. What changes are you wanting to make to the models?

**Comment by GraphGrail** [comment]
I want to add fields to class Account(models.Model) to allow set additional information.
By the way i dont use virtualenv.
Yes, i need templates, because i faced this error:
'bootstrap' is not a valid tag library: Template library bootstrap not found,
i have installed some bootstrap for forms, but there are a lot of apps on github with the same name and cannot find appropriate.

**Comment by GraphGrail** [comment]
Is there anyone to explain where files and folders of pinax starter?
I see in template: {% extends "theme_bootstrap/subnav_base.html" %}  but i reallly cannot find where is files of theme_bootstrap

**Comment by GraphGrail** [comment]
I found files on my python site-packages.
Now i need bast practices on how do i change templates and models for my purposes.

**Comment by jtauber** [comment]
If you have a template in your project with the same name as one in the theme it will override the one provided by the theme. Note this is just a Django thing, nothing specific to Pinax or the theme.
