### ISSUE TITLE
Example for account.hooks.AccountDefaultHookSet

### ISSUE THREAD

**Issue by jermsv1** [pinax/django-user-accounts#193]
I'm trying to figure out how to implement a custom hook for 

send_invitation_email or any other hookable things... can you provide an example?

**Comment by brosner** [comment]
An example is a good idea. I did a Pinax hangout session which covered this in detail. The relevant part of the video is here https://youtu.be/iun7y4hz0gg?t=1413

**Comment by jermsv1** [comment]
Thank you very much!
