### ISSUE TITLE
Django 1.8: django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet

### ISSUE THREAD

**Issue by GraphGrail** [pinax/django-user-accounts#197]
I explained issue here:  http://stackoverflow.com/questions/34117430/django-1-8-django-core-exceptions-appregistrynotready-models-arent-loaded-yet

**Comment by brosner** [comment]
I suspect there is an issue at your project layer or a different app. We've taken many steps to ensure we don't call `get_user_model` before the app cache is loaded.

See previous discussion at https://github.com/pinax/django-user-accounts/issues/113

Closing until more details emerge.
