### ISSUE TITLE
problem with ConfirmEmailView class

### ISSUE THREAD

**Issue by delchiv** [pinax/django-user-accounts#198]
I have python==2.7.11, django==1.9, django-user-accounts==1.3.0.

There is problem in ConfirmEmailView class in get_context_data method. There is no such method in parent classes. So you need to add ContextMixin from django.views.generic.base to parents or change ctx = super(ConfirmEmailView, self).get_context_data(**kwargs) line.

**Comment by brosner** [comment]
Confirmed. I am going to write a test to ensure we are smoke testing `ConfirmEmailView`.

**Comment by brosner** [comment]
Fixed in d974362039d20cf9bf7f45a4bab0135435049870. I am going to issue 1.3.1 with the fix as well.
