### ISSUE TITLE
Where do I put templates?

### ISSUE THREAD

**Issue by gummz** [pinax/django-user-accounts#201]
Greetings, thanks for DAU.

Where do I put these? Examples:

account/email/email_confirmation_subject.txt
account/signup_closed.html

Tried putting them into the site-packages/account/ and django_project/account, neither worked.

**Comment by brosner** [comment]
Templates need to go in your project at the location defined by your `TEMPLATES[0]["DIRS"]` path in your `settings.py`.

**Comment by gummz** [comment]
Thanks for the reply. This is my DIRS: http://i.imgur.com/RmTPvOA.png

The BASE_DIR is 

    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

and this is the project structure: http://i.imgur.com/JVKFTOa.png
