### ISSUE TITLE
About restful api framework integrated.

### ISSUE THREAD

**Issue by monalisir** [pinax/django-user-accounts#203]
Hello, 
I'm using pinax, it's very easy to startup a base website with user accounts, for the mobile app is very popular, do you have any plan to integrate some restful framework, such as django-rest-freameworkl. or is there some tutorial ?
Thanks.

**Comment by brosner** [comment]
This is something on our minds and looking to solve. Unfortantely, I can't offer you a solution now, but give you the peace of mind that it is something we are solving.

**Comment by ossanna16** [comment]
@monalisir Does this answer your question, meaning can I close this issue? 😊

**Comment by monalisir** [comment]
@ossanna16 @brosner Thanks. Waiting your new updates.

**Comment by ossanna16** [comment]
Thank you @monalisir!
