### ISSUE TITLE
User filter in  /admin/account/emailaddress/

### ISSUE THREAD

**Issue by tbazadaykin** [pinax/django-user-accounts#213]
I have a site where almost 10 000 users. On the page ` /admin/account/emailaddress/`, there is a standard filter for the users. So, to generate a list of items to 10,000 require a sizeable amount of time, not to mention the fact that it is useless in this form. Since the search for the name of the user is possible through a search bar offers a standard filter is turned off.

**Comment by ossanna16** [comment]
@tbazadaykin I'm not quite sure I understand the issue. You are saying that it takes too long to generate a list of your 10,000 users, and that you think the standard user filter is basically useless is that correct? But what exactly is the issue or what would you like us to do? Thank you for clarifying?

**Comment by tbazadaykin** [comment]
Yes, this is correct.
I see that you already removed `list_display` from `EmailAddressesAdmin`. It seems I have an old version =(.
Sorry, I was not attentive.

**Comment by jtauber** [comment]
@tbazadaykin no problem. I'll close this if that's okay. (Reopen if still relevant).
