### ISSUE TITLE
Error when confirming email

### ISSUE THREAD

**Issue by dmartincc** [pinax/django-user-accounts#216]
Hi,

when I receive an email in order to be confirmed a get the following error:

`AttributeError at /account/confirm_email/44ae0e6695eb79683bffa259c1d8acea76fdd986966d60e5fb239657807739ab/
'super' object has no attribute 'get_context_data'`

Any clue?

**Comment by dmartincc** [comment]
I just notice that this bug is solved in the following commit [d974362039d20cf9bf7f45a4bab0135435049870](https://github.com/pinax/django-user-accounts/commit/d974362039d20cf9bf7f45a4bab0135435049870)

when is version 1.4 coming out?

**Comment by brosner** [comment]
You don't need to wait for 1.4. That fix is in 1.3.1.

**Comment by dmartincc** [comment]
Many thanks
