### ISSUE TITLE
Password fields are stripping spaces (django >= 1.9)

### ISSUE THREAD

**Issue by irothschild** [pinax/django-user-accounts#222]
The form fields for password need `strip=False` starting in django 1.9 otherwise spaces will be stripped.

**Comment by ossanna16** [comment]
@irothschild Would you mind sending in a PR for this? We'd appreciate it :)

**Comment by jtauber** [comment]
Is stripping spaces a bad thing, though? I think a design discussion is needed.

**Comment by irothschild** [comment]
If someone had a space at beginning or end of password they can no longer log in. Fine for new signups.

**Comment by jtauber** [comment]
I realize that but I feel like we should have been stripping them all along.

**Comment by jtauber** [comment]
so there's a tradeoff between backwards incompatibility and "doing the right thing" move forward. Hence the need for discussion.

**Comment by irothschild** [comment]
Yeah. For the project I'm working on, the people don't want them stripped... that's how I realized there was an issue.

**Comment by jtauber** [comment]
I wonder if we should just make it settable (but stripped by default) to handle your case @irothschild

**Comment by brosner** [comment]
I agree with @jtauber here. For 2.0, let's add the setting, but default it to stripping by default.
