### ISSUE TITLE
MIDDLEWARE_CLASSES in Django 1.10

### ISSUE THREAD

**Issue by RezaOptic** [pinax/django-user-accounts#230]
in django 1.10 MIDDLEWARE_CLASSES changed to MIDDLEWARE and when i use this
 ```
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'account.middleware.LocaleMiddleware',
    'account.middleware.TimezoneMiddleware',
    'account.middleware.ExpiredPasswordMiddleware',
]
```
i take this 
[err.txt](https://github.com/pinax/django-user-accounts/files/502620/err.txt)

and when i remove 
` 'account.middleware.ExpiredPasswordMiddleware'`
i take this err 
[err2.txt](https://github.com/pinax/django-user-accounts/files/502639/err2.txt)

django-user-accounts doesn't support django 1.10 ?

**Comment by paltman** [comment]
I'm using the latest release of DUA in a number of Django 1.10 projects with no problems.  The `ExpiredPasswordMiddleware` is currently on `master` and not in a release yet.  We will investigate this issue but I suspect there is something else going on given that error you are seeing in `err2.txt`.

**Comment by paltman** [comment]
@RezaOptic there does seem to be an issue with the middleware.  for now just remove the `account.middleware.*`.

**Comment by brosner** [comment]
Fixed on master.
