### ISSUE TITLE
DEFAULT_HTTP_PROTOCOL doesn't appear to be working

### ISSUE THREAD

**Issue by amberdiehl** [pinax/django-user-accounts#237]
My site runs under HTTPS. I set the above setting to be HTTPS for PasswordResetView. However, the URL being returned in the password reset now is:

https://http://127.0.0.1:8000/account/password/reset/5-4h6-570f2a04577f452720df/

And when I remove the setting, I get this:

http://http://127.0.0.1:8000/account/password/reset/5-4h6-570f2a04577f452720df/

Is there a setting I'm missing or is this a bug?

**Comment by amberdiehl** [comment]
Any thoughts about this?

**Comment by dracos** [comment]
Your 'domain' in your Site model should be just the domain (and port), not including the 'http://' that it includes, which is why you're getting it twice.

**Comment by amberdiehl** [comment]
My apologies; you are correct. Thank you very much for your response.
