### ISSUE TITLE
Django 1.11 ? and python 3.6 

### ISSUE THREAD

**Issue by maks-us** [pinax/django-user-accounts#261]
Hi 
Does it work for fresh python django ? 
We have missing description in readme if it works with fresh python and django.

**Comment by jr-hypertext** [comment]
HI maks-us to answer your question if it is working with django 1.11 and python 3.6 , Yes it is working ive just finish a project with those requirements.

**Comment by brosner** [comment]
Django 1.11 and Python 3.6 are supported since 2.0.1. The README was missed in the update to add support for them.
