### ISSUE TITLE
error: TemplateDoesNotExist at /account/login/

### ISSUE THREAD

**Issue by zhangzq** [pinax/django-user-accounts#276]
Please help. My django version is 1.11.7

Template-loader postmortem

Django tried loading these templates, in this order:

Using engine django:
django.template.loaders.filesystem.Loader: /home/zhangzq/autoweb/static/account/login.html (Source does not exist)
django.template.loaders.filesystem.Loader: /home/zhangzq/autoweb/templates/account/login.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/zhangzq/.local/lib/python2.7/site-packages/django/contrib/admin/templates/account/login.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/zhangzq/.local/lib/python2.7/site-packages/django/contrib/auth/templates/account/login.html (Source does not exist)

**Comment by paltman** [comment]
```
pip install pinax-templates
```

```python
# settings.py
INSTALLED_APPS += [
    "pinax.templates"
]
```
