### ISSUE TITLE
Disable signup and delete account for users?

### ISSUE THREAD

**Issue by koddr** [pinax/django-user-accounts#279]
Hello.

I don't want to get to my simple users (not stuff/superusers) signup/delete function. Now, they may write url, like `/accounts/signup/` and `/accounts/delete/` to use this function. How to disable them?

Thanks!

**Comment by reillychase** [comment]
I would probably copy urls.py from the module, add it to your app folder, then edit those two URLs and direct them to homepage or something like that. I'm not an expert though, just an idea

**Comment by paltman** [comment]
In your `settings.py`:

```python
ACCOUNT_OPEN_SIGNUP = False
```

This will do the trick.
