### ISSUE TITLE
Clarify Django 2.0 support

### ISSUE THREAD

**Issue by ckeeney** [pinax/django-user-accounts#281]
I ran into #228 when trying to upgrade to Django 2.0.  This issue has the milestone `post-2.0.0`.  

The [README](https://github.com/pinax/django-user-accounts/blob/master/README.rst#requirements) does not list this project as being compatible with Django 2.0:
> ## Requirements
> - Django 1.8, 1.9, 1.10 and 1.11

[This blog post](http://blog.pinaxproject.com/2018/02/01/django-20-stripe-connect-templates-patches/) says

> Pinax 18.01 brings support for Django 1.11 and 2.0 alongside Python 2.7, 3.4, 3.5, and 3.6. 

and 

> All updated Pinax apps support the following pairings: Django 1.11 on Python 2.7, 3.4, 3.5, and 3.6, and Django 2.0 on Python 3.4, 3.5, and 3.6.

Can we get clarification on the current support for Django 2.0?

**Comment by KatherineMichel** [comment]
Closing issue. A release was published a few days later that included Django 2.0. https://github.com/pinax/django-user-accounts/releases/tag/v2.1.0

**Comment by ckeeney** [comment]
>  a few days later

Or 8 months... but thanks for the update anyways.
