### ISSUE TITLE
Management command for clearing sessions

### ISSUE THREAD

**Issue by jtauber** [pinax/django-user-accounts#29]

**Comment by ossanna16** [comment]
Any further discussion on this? 😊

**Comment by jonathan-s** [comment]
Clearing sessions can be done with the [management command described in the documentation](https://docs.djangoproject.com/en/2.2/ref/django-admin/#django-contrib-sessions)

**Comment by paltman** [comment]
@jtauber I don't think this is a problem anymore now that we have a command baked into Django
