### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by cptnsx** [pinax/django-user-accounts#291]
Are any logs written by this?  My developer states he cannot find any log files that are generated by django-user-accounts.  Is there a location he should be looking for or did he install this wrong without the correct settings, flags to enable logging.  Or is it just email notifications?

**Comment by jtauber** [comment]
There are various signals fired for events which can be received and acted on (although this is not done in the app itself). In Pinax starter projects, the signals are logged to the database using pinax-eventlog. See https://github.com/pinax/pinax-starter-projects/blob/account/project_name/receivers.py for examples.

Hope this helps!
