### ISSUE TITLE
Can not login to Django admin

### ISSUE THREAD

**Issue by aientrp** [pinax/django-user-accounts#295]
I use this option https://django-user-accounts.readthedocs.io/en/latest/usage.html#using-email-address-for-authentication
with "account.auth_backends.EmailAuthenticationBackend" use I can not login to Admin 
I use python37 django21

**Comment by tyndyll** [comment]
It looks like there is a PR in for this (https://github.com/pinax/django-user-accounts/pull/293)

**Comment by KatherineMichel** [comment]
Closing issue because appears to have been dealt with through merged PR #293
