### ISSUE TITLE
THEME_CONTACT_EMAIL 

### ISSUE THREAD

**Issue by BurgLiu** [pinax/django-user-accounts#296]
Could you please tell me how to set THEME_CONTACT_EMAIL ?  
Is it the EMAIL_HOST_USER in "settings.py" file?

**Comment by KatherineMichel** [comment]
@BurgLiu I think you put ```THEME_CONTACT_EMAIL = 'example@email.com'``` in the settings.py. I think this is then used in context_processors.py file.

**Comment by BurgLiu** [comment]
Thanks for your reply.  I have solved this problem.  A context_processors.py file should be added to context_processors. 


> 
> 
> @BurgLiu I think you put `THEME_CONTACT_EMAIL = 'example@email.com'` in the settings.py. I think this is then used in context_processors.py file.

**Comment by jonathan-s** [comment]
Might be worth adding this to the documentation. When for this in the docs there is no mention about it.
