### ISSUE TITLE
version 2.1 requires django >=1.11 but requirements section states django 1.8

### ISSUE THREAD

**Issue by klausfmh** [pinax/django-user-accounts#302]
on https://pypi.org/project/django-user-accounts/2.1.0/ it is stated, that django-user-accounts supports django 1.8, but when trying to install it I get
`django-user-accounts 2.1.0 has requirement Django>=1.11, but you'll have django 1.8.19 which is incompatible.`

This is just a documentation bug.

**Comment by klausfmh** [comment]
Made a PR:
https://github.com/pinax/django-user-accounts/pull/303

**Comment by KatherineMichel** [comment]
Closing issue based on comment on PR.
