### ISSUE TITLE
Why does ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS need to have a value?

### ISSUE THREAD

**Issue by jh-sportcaster** [pinax/django-user-accounts#310]
Recommended label: For discussion.

Looking over the documentation, and the code, it's clear that email confirmation expiry is non-negotiable, but I'm wondering why. (I realise that you can fake non-expiry by just providing a huge number, but that still doesn't explain why it's a requirement.)

Are there any security considerations I'm overlooking when thinking that I should just never expire them?

**Comment by KatherineMichel** [comment]
It looks like email confirmation itself is optional. Expire setting could be to prevent the verification email from being used if the email account is compromised maybe. Or to keep the user database current. You can also fork DUA and make it a conditional setting yourself if you want. https://github.com/pinax/django-user-accounts/blob/master/account/models.py#L326

**Comment by jh-sportcaster** [comment]
Katherine,

Thanks for your reply.

I understand that confirmation is optional (although I forgot to mention it, my bad), but I *do* want confirmation; I'm just trying to work out why I would necessarily want the confirmation request to expire.

Your suggestions seem reasonable, I'm just not personally particularly worried about either case, so if those are the justifications, I think I will go ahead with my workaround. (I could fork, but I'd rather not keep it up to date.)

I'll leave the issue open in case someone else has an opinion on the matter, but I'd accept it being closed.

**Comment by jtauber** [comment]
I'm certainly not against making it optional and putting the onus on the site developer.

It's a _very_ common practice to expire these sorts of things, though, which is why we implemented it the way we did. I don't think it occurred to us someone would not want to expire it.

I'll close this but happy to consider a PR making it optional.
