### ISSUE TITLE
css are not applied to the page

### ISSUE THREAD

**Issue by sbohora** [pinax/django-user-accounts#329]
I am using `account` to start an app, but I see the css formats are not applied to the page even after doing `collectstatic`. Does it need to be packaged using `npm install`? Any help would be appreciated. Thanks.

![image](https://user-images.githubusercontent.com/9141145/80136137-27d25980-8556-11ea-980b-ed51a8cce165.png)

**Comment by KatherineMichel** [comment]
The front end needs to be run using npm. I usually use two terminal windows... one for Django and one for npm. There are some instructions that might help under "Modern Local Development Step" section of the docs. The CSS and templates should come bundled with the project. Let me know if you have any other questions. 
https://pinaxproject.com/pinax/quick_start/
