### ISSUE TITLE
Prefetch Account model for User

### ISSUE THREAD

**Issue by maxifom** [pinax/django-user-accounts#340]
**Is your feature request related to a problem? Please describe.**
I got a list of 100 models, each connected to django User model. For each model I get a DB request to accounts table to select it.

**Describe the solution you'd like**
Something like prefetch_related working in django. I want something like in User model get_queryset:
qs = qs.prefetch_related('account')
As I found out this function triggers DB request: 
```
account.context_processors.account -> Account.for_request
```
which just uses Account.get().

**Additional context**
![image](https://user-images.githubusercontent.com/20924207/104688050-33883080-5722-11eb-9df7-e64129d2dca0.png)

**Comment by maxifom** [comment]
as i suggestion, maybe could use 
`if hasattr(user_instance, "account)": return user_instance.account else fetch from db`
that way we can prefetch it on user model

**Comment by jonathan-s** [comment]
@maxifom Would the following #351 solve your issue?

**Comment by paltman** [comment]
Please reopen if not fixed in #351
