### ISSUE TITLE
Call for Maintainers

### ISSUE THREAD

**Issue by paltman** [pinax/django-user-accounts#368]
Looking for maintainers!

There is a lot of pull requests and open issues that the current maintainers, myself included, are just not finding the time to properly get to.

Maybe you've submitted some PRs and are frustrated with the lack of attention.  Maybe you use this project in one or more of your projects and want to see that it is properly carried forward.

Whatever you reasons may be, let me know if you have interest and I'll add you to the repo and to PyPI (will need your PyPI name).  

Preference will go to those who have commits on this repo and/or have shown an active interest in the issues.

Thanks!
Patrick

**Comment by blag** [comment]
I can't commit to being a long-term maintainer, but I can at least do some issue and PR triage, merge a few PRs, and publish a new release or two. I've been the maintainer of a few different open source projects/packages over the years, I'm an active Django user, I've been a user of django-user-accounts for roughly ten years, I have an open PR, I've reviewed some other PRs and issues, and I occasionally pop onto the Pinax Slack workspace.

I'm also blag on PyPI and Slack.

**Comment by paltman** [comment]
@blag thanks so much!  added!

I'll leave this open in case anyone else once to join you.

**Comment by uhurusurfa** [comment]
@paltman Add me to this too please.

**Comment by blag** [comment]
I saw the PyPI invite but not a GitHub invite yet.

**Comment by paltman** [comment]
You look all set to me now.  Guessing it eventually came through?

**Comment by paltman** [comment]
@uhurusurfa added!  I'll leave it to you and @blag to figure out how you'll want to coordinate.

**Comment by blag** [comment]
Yep, turns out it was a PEBCAK, sorry for the noise.

@uhurusurfa I will likely have some time this weekend to start merging PRs.

**Comment by aglili** [comment]
I would also be interested

**Comment by uhurusurfa** [comment]
@agilili - I have added you
