### ISSUE TITLE
Default timezone in TimeZoneField isn't a valid timezone code

### ISSUE THREAD

**Issue by thomasgilgenast** [pinax/django-user-accounts#67]
In `account.models.Account`, the `language` field has an appropriate default and then is handled again in `create()` to make sure that a newly created `Account` has a valid `language`. This is not the case for the `timezone` field. It is not touched in `create()`, and no default is provided in the field declaration. There is a default in the `TimeZoneField` class, but this default is just the empty string, which does not correspond to a valid timezone. Even in terms of database integrity, I was surprised to look at my database and see that my freshly created `User` had an `Account` with a non-null, non-blank field set to the empty string.

Either the `TimeZoneField` or the `timezone` field declaration in `Account` should specify a default that corresponds to a valid timezone.

**Comment by thomasgilgenast** [comment]
Sorry to comment on this so long after the fact. I should have indicated how to reproduce the error I was seeing (exceptions being thrown when no time zone is set at the OS level). It must have happened to me at least once to prompt me to open the issue but without including a way to reproduce it I am not sure I can say anything about what kind of distro/installation process would lead to the user having no timezone set. Feel free to close this due to being non-reproducible or just being inactive for too long.

**Comment by paltman** [comment]
@thomasgilgenast thanks.  I'm going through old PRs and issues with a goal to get a new release out in the coming days. Maintaining open source is hard and will have to make some decisions for the sake of progress and it will likely mean closing things that are really old.  Please do not take that as a lack of appreciation for the contributions.  That couldn't be further from the truth.
